DefaultProfile: profile
DefaultRegion: us-west-2
DefaultDurationForMFA: 2600
DefaultDecisionForMFA: false
DefaultVerbosity: ERROR
SpecificationURL:
  us-west-2: "https://d1uauaxba7bl26.cloudfront.net"
